### ISSUE TITLE
Invalid value used as weak map key

### ISSUE THREAD

**Issue by janlin002** [jotaijs/jotai-signal#13]
I'm trying to follow a [tutorial](https://codesandbox.io/s/github/jotai-labs/jotai-signal/tree/main/examples/01_typescript?file=/src/App.tsx:0-839), but I encountered the following problem: "Invalid value used as weak map key". How can I solve this issue?

**Comment by janlin002** [comment]
<img width="488" alt="截圖 2023-03-22 上午11 55 53" src="https://user-images.githubusercontent.com/68535430/226798271-246a520e-f6cb-4b04-a4c4-ee1896095cad.png">

**Comment by janlin002** [comment]
I have solved the problem. I realized that I imported `useAtom` and `useSetAtom` incorrectly, I wrote `jotai` instead of `jotai/react`.

**Comment by dai-shi** [comment]
Hmm? Wouldn't it be the same?
```js
import { useAtom } from 'jotai';
import { useAtom } from 'jotai/react';
```

**Comment by janlin002** [comment]
https://codesandbox.io/s/recursing-cray-j0c9uc?file=/src/App.js
This is a simple demo and I noticed that if I use "$" like a useState hook(`const [a, b] = useAtom(initvalue)`), it will result in an error(`Invalid value used as weak map key`). However, if I declare them separately, it works correctly.

**Comment by dai-shi** [comment]
You want to pass an atom object to `$()`, so in your case, it's `$(initCount)`.

**Comment by janlin002** [comment]
Understood, thank you for your response.
