### ISSUE TITLE
should it run on react-native?

### ISSUE THREAD

**Issue by ph4un00b** [jotaijs/jotai-signal#9]
Hello ✋, Very cool library, but I was wondering if the signals should work on react-native since I'm more into that workflow these days.
Right now i'm not able to display an expected value.

![image](https://user-images.githubusercontent.com/1057021/218608996-fd540e7d-a370-45a4-ae16-889fbd475764.png)

tsconfig
![image](https://user-images.githubusercontent.com/1057021/218609252-eca5b35c-e793-4b2e-8b55-bdecfff94f72.png)

**Comment by dai-shi** [comment]
Hi, thanks for trying!
Technically, it should work on RN, but I never tried.
Can you create a small reproduction with expo snack?

**Comment by dai-shi** [comment]
Thanks.

I just hand-compiled: https://snack.expo.dev/kjclneke1

You are right, it's not working... 🤔

**Comment by dai-shi** [comment]
I hope to find some time to work on it. It will take a while.

**Comment by dai-shi** [comment]
Hi, I tried to reproduce the bug locally, but it works well locally.
I downloaded the expo snack and run locally on web and iOS.

Also tried, codesandbox with react-native-web: https://codesandbox.io/s/priceless-star-kg7dmh?file=/src/App.js, it's working well.

What's missing? Can you help creating a reproduction?

**Comment by dai-shi** [comment]
> https://github.com/ph4un00b/jotai-signals-typescript

I think you just forgot the jsx pragma?

```diff
diff --git a/App.tsx b/App.tsx
index 3271b1c..8427f78 100644
--- a/App.tsx
+++ b/App.tsx
@@ -1,3 +1,5 @@
+/** @jsxImportSource jotai-signal */
+
 import { Text, View, StyleSheet, Button } from "react-native";
 import { atom } from "jotai/vanilla";
 import { useAtom, useSetAtom } from "jotai/react";
```

**Comment by dai-shi** [comment]
that syntax error is due to that the bundler can't resolve `jotai-signal/jsx-runtime`. maybe, you need something in metro config.

**Comment by dai-shi** [comment]
@ph4un00b that's great to know. thanks.

@muhammadaasim from https://github.com/dai-shi/zustand-signal/issues/13, this issue should be helpful for you.
